### ISSUE TITLE
Stops Controller Input

### ISSUE THREAD

**Issue by ljford7** [simonowen/dashfix#4]
Hi,

I have been using this, but ran into a fairly substantial bug. I SIM race and use a Fanatec ClubSport Wheel Base V2.5 wheel and dashfix causes it to stop working randomly. I have to reboot the computer to get it to work again. One time, the wheel started working again after 30 seconds, but most of the time it doesn't work again. My guess is that the inputs from the wheel are being blocked globally in lieu of just in the dashboard.

Thanks!

**Comment by simonowen** [comment]
Dashfix only injects the hooking DLL into Steam.exe and vrdashboard.exe, and doesn't use a device driver. That means it's not in the address space of any other process in the system, and can't directly affect them.  If you're seeing input issues in other processes then it's likely to be an issue with the Fanatec drivers or hardware, since they're the only factor that has global reach.

I've been using Dashfix with a Fanatec CSW V2 the whole time, though my drivers are probably out of date.  I may not be able to match firmware versions with your V2.5, but if you let me know which driver version you're using I'll update mine and see if I see any issues.

It would also be useful if you could launch Dashfix again, uncheck the Start with Windows option, click OK and then reboot.  Dashfix should no longer be running and will be completely inactive.  Carry on sim-racing and see if you run into the same issue again.

**Comment by ljford7** [comment]
I was using beta driver v281. They also just issued a new beta driver v289 that I have yet to try. 

https://www.fanatec.com/forum/discussion/551/fanatec-beta-driver-v289-for-csw-v1-csw-v2-csw-v2-5-csl-e-wb-csl-e-ps4#latest

I have completely disabled dashfix and the issue has gone away, so I know that dashfix is part of the issue (I also didn't have this issue prior to using dashfix).

Another issue that might be related is that SteamVR has a bug (introduced in the latest sable version and still in the beta version) where you have to load it prior to loading a game or the FFB of the wheel won't engage in the game. I know rFactor 2 and iRacing both have this problem. Maybe this issue is messing up dashfix as well?

**Comment by simonowen** [comment]
Thanks for the extra details!

I seem to be running v261, so I'll give v281 a try as I know you saw the issue with that.  I've mostly been on the stable SteamVR, which I tend to start manually to make sure it's settled before launching games.  I've been meaning to give the rFactor 2 VR support a try, so now's the perfect excuse!

I checked the Dashfix startup code to confirm it just sits watching for Steam and the VR dashboard processes when launched on Windows startup.  When the processes are found it injects the DLL, which patches a function in the SDL2 library.  However, none of that touches any controller input.  It's Steam and the VR dashboard that open the controller, and when one is blocked it fakes a zero input position, without even passing the call through to the real controller.

The only time Dashfix touches the controllers is when the GUI is launched, when it builds a list of local controllers.  During Windows startup it's launched in a mode that doesn't show the GUI, which means it doesn't touch the hardware.  It's only when launching Dashfix again that it shows the GUI, so if you've not done that between starting Windows and seeing the issue then there shouldn't be any interaction.

It still feels like a driver issue, which I'll continue to try and reproduce here with v281 beta.  If I can see it, I'll find a way to work around it, wherever the issue lies.  Any tips on helping reproduce it would be appreciated.

**Comment by ljford7** [comment]
OK, I ended up completely reinstalling Steam and now Dashfix seems to be working as intended. I ran a race last night and didn't have any issues.

Theory on what was happening:

I think I had a button mapped from my wheel directly in Steam. When I would press the brake button in iRacing the Steam dashboard would come up and then nothing would work in iRacing (I also use a program called AntiMicro to map buttons on the wheel which further complicated this issue). Dashfix wouldn't/couldn't prevent this from happening even when it was running (which is strange because I thought it would, but for some reason button presses were getting through). 

I do remember reading that mapping the controller buttons in Steam would fix the issue that Dashfix fixes and I must have went that route at one time, but it didn't work. I tried to remove the wheel controllers from Steam, but there was not way to do that without reinstalling Steam (which is a crappy design on Steam's part). 

Thank you for your help with this!

Also, is Dashfix running as an Administrator in the background? I usually use Task Scheduler to start programs to make them run as an Administrator (seems to fix a lot of strange issues). Dashfix isn't listed in the startup programs on Task Manager, but is running in the background.

I do have a small suggestion for the program. To me it is confusing that you have to uncheck the box in Dashfix to block the controller and more intuitive (to me) to have to check the box to block it.

Once again thank you for the program and bearing with me trying to troubleshoot!

**Comment by simonowen** [comment]
Glad to hear you're sorted!  I had an hour or so on rFactor 2 using v281 without noticing any issues, and was due to get some more laps in today.

The current input block is just the analogue axis, as it tends to be brake or accelerator causing issues.  That could be extended to cover buttons and other input if it'd help.  It would still only be blocked from within Steam and the VR dashboard, of course.

Dashfix runs as a regular non-elevated user.  It just needs to be at the same privilege level as Steam.exe and vrdashboard.exe, so it can open their processes to inject the DLL.  They're generally run non-elevated too, so the lowest level is fine.

You're right, it would make more sense to check the box to block.  It should be easy enough to invert the logic without changing how the settings are stored, so the updated version still blocks the right controllers for existing users.  It's probably time I wrapped it up in an installer too.

Thanks for your help in getting to the bottom of this  :)
